
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class LanguageConfigCategory : CategoryBase
{
    public static LanguageConfigCategory Instance;
    
    private System.Collections.Generic.Dictionary<int, LanguageConfig> _dataMap;
    private System.Collections.Generic.List<LanguageConfig> _dataList;
   
    
    public override void Load(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, LanguageConfig>();
        _dataList = new System.Collections.Generic.List<LanguageConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            LanguageConfig _v;
            _v = LanguageConfig.DeserializeLanguageConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        
        Instance = this;
    }

    public System.Collections.Generic.Dictionary<int, LanguageConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<LanguageConfig> DataList => _dataList;

    public LanguageConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LanguageConfig Get(int key) => _dataMap[key];
    public LanguageConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
