
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class ConditionGroupConfig : Luban.BeanBase
{
    public ConditionGroupConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LogicType = (LogicType)_buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Conds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Conds.Add(_e0);}}
    }

    public static ConditionGroupConfig DeserializeConditionGroupConfig(ByteBuf _buf)
    {
        return new ConditionGroupConfig(_buf);
    }

    /// <summary>
    /// 不能复用!每个组只能被一个地方引用
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 条件之间的关系<br/>默认And(条件要全部满足)
    /// </summary>
    public readonly LogicType LogicType;
    /// <summary>
    /// 组内条件
    /// </summary>
    public readonly System.Collections.Generic.List<int> Conds;
   
    public const int __ID__ = -742913370;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "LogicType:" + LogicType + ","
        + "Conds:" + Luban.StringUtil.CollectionToString(Conds) + ","
        + "}";
    }
}

}
