
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class NumericConfigCategory : CategoryBase
{
    public static NumericConfigCategory Instance;
    
    private System.Collections.Generic.Dictionary<int, NumericConfig> _dataMap;
    private System.Collections.Generic.List<NumericConfig> _dataList;
   
    
    public override void Load(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, NumericConfig>();
        _dataList = new System.Collections.Generic.List<NumericConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            NumericConfig _v;
            _v = NumericConfig.DeserializeNumericConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        
        Instance = this;
    }

    public System.Collections.Generic.Dictionary<int, NumericConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<NumericConfig> DataList => _dataList;

    public NumericConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public NumericConfig Get(int key) => _dataMap[key];
    public NumericConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
