
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{ 
    public enum NumericType
    {
        /// <summary>
        /// 特殊用途
        /// </summary>
        None = 0,
        /// <summary>
        /// 当前血量
        /// </summary>
        HP = 1001,
        /// <summary>
        /// 最大血量
        /// </summary>
        MaxHP = 1002,
        /// <summary>
        /// 最大血量
        /// </summary>
        MaxHP_Base = 10021,
        MaxHP_Add = 10022,
        MaxHP_Pct = 10023,
        /// <summary>
        /// 移动速度
        /// </summary>
        MoveSpeed = 1003,
        /// <summary>
        /// 移动速度
        /// </summary>
        MoveSpeed_Base = 10031,
        MoveSpeed_Add = 10032,
        MoveSpeed_Pct = 10033,
        /// <summary>
        /// 等级
        /// </summary>
        Level = 1004,
        /// <summary>
        /// 攻击力
        /// </summary>
        ATK = 1005,
        /// <summary>
        /// 攻击力
        /// </summary>
        ATK_Base = 10051,
        ATK_Add = 10052,
        ATK_Pct = 10053,
        /// <summary>
        /// 防御力
        /// </summary>
        DEF = 1006,
        /// <summary>
        /// 防御力
        /// </summary>
        DEF_Base = 10061,
        DEF_Add = 10062,
        DEF_Pct = 10063,
        /// <summary>
        /// 攻速
        /// </summary>
        AttackSpeed = 1007,
        /// <summary>
        /// 攻速
        /// </summary>
        AttackSpeed_Base = 10071,
        AttackSpeed_Add = 10072,
        AttackSpeed_Pct = 10073,
    }

} 

