
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
public partial class Tables
{

    public Tables(System.Func<string, ByteBuf> loader)
    {
        new NumericConfigCategory().Load(loader("NumericConfigCategory"));
        new ConditionGroupConfigCategory().Load(loader("ConditionGroupConfigCategory"));
        new ConditionConfigCategory().Load(loader("ConditionConfigCategory"));
        new LanguageConfigCategory().Load(loader("LanguageConfigCategory"));
        new TimeScheduleConfigCategory().Load(loader("TimeScheduleConfigCategory"));
        new UnitConfigCategory().Load(loader("UnitConfigCategory"));
        new LevelConfigCategory().Load(loader("LevelConfigCategory"));
        ResolveRef();
        OnDeserialize();
    }
    
    private void ResolveRef()
    {
        NumericConfigCategory.Instance.ResolveRef(this);
        ConditionGroupConfigCategory.Instance.ResolveRef(this);
        ConditionConfigCategory.Instance.ResolveRef(this);
        LanguageConfigCategory.Instance.ResolveRef(this);
        TimeScheduleConfigCategory.Instance.ResolveRef(this);
        UnitConfigCategory.Instance.ResolveRef(this);
        LevelConfigCategory.Instance.ResolveRef(this);
    }
    
    private void OnDeserialize()
    {
        NumericConfigCategory.Instance.OnDeserialize();
        ConditionGroupConfigCategory.Instance.OnDeserialize();
        ConditionConfigCategory.Instance.OnDeserialize();
        LanguageConfigCategory.Instance.OnDeserialize();
        TimeScheduleConfigCategory.Instance.OnDeserialize();
        UnitConfigCategory.Instance.OnDeserialize();
        LevelConfigCategory.Instance.OnDeserialize();
    }
}

public abstract class CategoryBase
{
    public virtual void OnDeserialize()
    {
        
    }
    
    public abstract void Load(ByteBuf _buf);
}


}
