
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class TimeScheduleConfig : Luban.BeanBase
{
    public TimeScheduleConfig(ByteBuf _buf) 
    {
        Id = (TimeScheduleType)_buf.ReadInt();
        CronStart = _buf.ReadString();
        CronEnd = _buf.ReadString();
        TimeInterval = (TimeRefreshType)_buf.ReadInt();
    }

    public static TimeScheduleConfig DeserializeTimeScheduleConfig(ByteBuf _buf)
    {
        return new TimeScheduleConfig(_buf);
    }

    /// <summary>
    /// 调度类型
    /// </summary>
    public readonly TimeScheduleType Id;
    /// <summary>
    /// Cron表达式
    /// </summary>
    public readonly string CronStart;
    /// <summary>
    /// Cron表达式
    /// </summary>
    public readonly string CronEnd;
    /// <summary>
    /// 刷新类型
    /// </summary>
    public readonly TimeRefreshType TimeInterval;
   
    public const int __ID__ = -996154106;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "CronStart:" + CronStart + ","
        + "CronEnd:" + CronEnd + ","
        + "TimeInterval:" + TimeInterval + ","
        + "}";
    }
}

}
