
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{ 
    /// <summary>
    /// 比较类型
    /// </summary>
    public enum CfgCompareType
    {
        /// <summary>
        /// 等于
        /// </summary>
        EQ = 0,
        /// <summary>
        /// 大于等于
        /// </summary>
        GE = 1,
        /// <summary>
        /// 大于
        /// </summary>
        GT = 2,
        /// <summary>
        /// 小于等于
        /// </summary>
        LE = 3,
        /// <summary>
        /// 小于
        /// </summary>
        LT = 4,
        /// <summary>
        /// 不等于
        /// </summary>
        NE = 5,
    }

} 

