
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{ 
    /// <summary>
    /// 条件类型
    /// </summary>
    public enum ConditionType
    {
        /// <summary>
        /// 队伍等级
        /// </summary>
        TeamLevel = 0,
    }

} 

