
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class ConditionGroupConfigCategory : CategoryBase
{
    public static ConditionGroupConfigCategory Instance;
    
    private System.Collections.Generic.Dictionary<int, ConditionGroupConfig> _dataMap;
    private System.Collections.Generic.List<ConditionGroupConfig> _dataList;
   
    
    public override void Load(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ConditionGroupConfig>();
        _dataList = new System.Collections.Generic.List<ConditionGroupConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ConditionGroupConfig _v;
            _v = ConditionGroupConfig.DeserializeConditionGroupConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        
        Instance = this;
    }

    public System.Collections.Generic.Dictionary<int, ConditionGroupConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ConditionGroupConfig> DataList => _dataList;

    public ConditionGroupConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ConditionGroupConfig Get(int key) => _dataMap[key];
    public ConditionGroupConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
