
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{ 
    public enum CurrencyType
    {
        /// <summary>
        /// 金币
        /// </summary>
        Gold = 0,
        /// <summary>
        /// 钻石
        /// </summary>
        Gem = 1,
    }

} 

