
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public sealed partial class LanguageConfig : Luban.BeanBase
{
    public LanguageConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CN = _buf.ReadString();
    }

    public static LanguageConfig DeserializeLanguageConfig(ByteBuf _buf)
    {
        return new LanguageConfig(_buf);
    }

    /// <summary>
    /// 从100,0000开始
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 中文显示
    /// </summary>
    public readonly string CN;
   
    public const int __ID__ = -1704465190;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "CN:" + CN + ","
        + "}";
    }
}

}
