
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class LevelConfigCategory : CategoryBase
{
    public static LevelConfigCategory Instance;
    
    private System.Collections.Generic.Dictionary<int, LevelConfig> _dataMap;
    private System.Collections.Generic.List<LevelConfig> _dataList;
   
    
    public override void Load(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelConfig>();
        _dataList = new System.Collections.Generic.List<LevelConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            LevelConfig _v;
            _v = LevelConfig.DeserializeLevelConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        
        Instance = this;
    }

    public System.Collections.Generic.Dictionary<int, LevelConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<LevelConfig> DataList => _dataList;

    public LevelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LevelConfig Get(int key) => _dataMap[key];
    public LevelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
