
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{ 
    /// <summary>
    /// 怪物类型
    /// </summary>
    public enum MonsterType
    {
        None = 0,
        /// <summary>
        /// 普通怪
        /// </summary>
        Normal = 1,
        /// <summary>
        /// 精英怪
        /// </summary>
        Elite = 2,
        Boss = 10,
    }

} 

