
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace ET
{ 
    /// <summary>
    /// 定时调度任务类型
    /// </summary>
    public enum TimeScheduleType
    {
        None = 0,
        /// <summary>
        /// 每日0点
        /// </summary>
        Daily0 = 1,
        /// <summary>
        /// 每周周一0点
        /// </summary>
        Weekly0 = 2,
        /// <summary>
        /// 每小时0分0秒
        /// </summary>
        Hour0 = 3,
    }

} 

