
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
public partial class TimeScheduleConfigCategory : CategoryBase
{
    public static TimeScheduleConfigCategory Instance;
    
    private System.Collections.Generic.Dictionary<TimeScheduleType, TimeScheduleConfig> _dataMap;
    private System.Collections.Generic.List<TimeScheduleConfig> _dataList;
   
    
    public override void Load(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<TimeScheduleType, TimeScheduleConfig>();
        _dataList = new System.Collections.Generic.List<TimeScheduleConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TimeScheduleConfig _v;
            _v = TimeScheduleConfig.DeserializeTimeScheduleConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        
        Instance = this;
    }

    public System.Collections.Generic.Dictionary<TimeScheduleType, TimeScheduleConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<TimeScheduleConfig> DataList => _dataList;

    public TimeScheduleConfig GetOrDefault(TimeScheduleType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TimeScheduleConfig Get(TimeScheduleType key) => _dataMap[key];
    public TimeScheduleConfig this[TimeScheduleType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
